# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 951e09ea65f73a2bd88bc90815584c4ddcce121227090dbbe9911906154d4fe9d1df783955d8741a12c3cf0a32b8df86151de48d76f8f6150dac531ce2f87a9d

test:
  secret_key_base: b1cf5db3ef9f818b393f274c2401c72d181cee66867241c053dffa6f44e0f1c0a5b081f651e0c575d2d9d05fd4576fb71823ab241a50eefe43220d237f3d849f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
